# Generated by Django 5.1.5 on 2025-02-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=100, verbose_name='Название главы')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(max_length=100, verbose_name='Название части курса')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=100, verbose_name='Название типа текста')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.IntegerField(verbose_name='Порядковый номер внутри главы')),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.chapter', verbose_name='id главы')),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.coursepart', verbose_name='id части')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.type', verbose_name='id типа текста')),
            ],
        ),
    ]
